/**
 * KeyVaultProvider — the normalized contract every key-vault backend implements.
 *
 * Orion never holds a long-lived symmetric key in configuration when a vault is
 * in play. Instead it uses ENVELOPE ENCRYPTION:
 *
 *   DEK (data encryption key)  — 32 random bytes, generated by Orion, used with
 *                                AES-256-GCM to seal individual field values.
 *   KEK (key encryption key)   — lives in the vault, never leaves it, and is
 *                                only ever asked to wrap/unwrap the DEK.
 *
 * Providers come in two physical shapes, and this file normalizes both to the
 * SAME four methods with the SAME return shapes:
 *
 *   'remote'   — the vault performs the crypto (AWS KMS, GCP KMS, Azure Key
 *                Vault, Vault/OpenBao transit, Akeyless, Infisical KMS). The
 *                KEK is never exposed; wrap/unwrap are network calls.
 *   'material' — the vault is a secret STORE and hands back key material
 *                (HCP Vault Secrets). The base class below performs the
 *                wrapping locally with the fetched material, so callers cannot
 *                tell the difference. See MaterialKeyVaultProvider.
 *
 * Contract (identical for every provider, both shapes):
 *
 *   await initialize()                        → resolves or throws KeyVaultError
 *   await wrapKey(dek)                        → { blob, keyRef, keyVersion, algorithm }
 *   await unwrapKey(blob, { keyRef, keyVersion }) → Buffer (32 bytes)
 *   await rotateKek()                         → { rotated, keyVersion, reason }
 *   await health()                            → { ok, provider, keyRef, keyVersion, latencyMs, error }
 *   capabilities                              → { mode, rotateKek, keyVersions, aad }
 *   await close()                             → void
 *
 * `blob` is ALWAYS an opaque ASCII string safe to store in a TEXT column. Its
 * internal shape is the provider's business — AWS returns a base64 ciphertext
 * blob, Vault returns `vault:v3:…`, Azure returns base64url. Nothing outside
 * the provider parses it.
 */

import crypto from 'crypto';

/** Every provider call is bounded so a slow vault cannot hang a worker. */
const DEFAULT_HTTP_TIMEOUT_MS = 10_000;

/** DEK size. AES-256-GCM — 32 bytes, non-negotiable across every provider. */
const DEK_BYTES = 32;

/**
 * Additional authenticated data bound to every wrap, on providers that support
 * it. Deliberately a CONSTANT: an AAD derived from deployment-specific values
 * (cluster name, hostname, config) would silently become unrecoverable the
 * moment an operator renamed something, which is the exact failure mode
 * envelope encryption exists to avoid.
 */
const WRAP_CONTEXT = Object.freeze({ purpose: 'orion:field-dek' });

class KeyVaultError extends Error {
    constructor(code, message, { provider = null, cause = null, retryable = false } = {}) {
        super(message);
        this.name = 'KeyVaultError';
        this.code = code;
        this.provider = provider;
        this.retryable = retryable;
        if (cause) this.cause = cause;
    }
}

// ─── Encoding helpers (shared by every provider) ─────────────────────────────

const b64 = buf => Buffer.from(buf).toString('base64');
const unb64 = str => Buffer.from(String(str), 'base64');
const b64url = buf => Buffer.from(buf).toString('base64url');
const unb64url = str => Buffer.from(String(str), 'base64url');

/**
 * JSON over HTTP with a hard timeout and uniform error translation.
 * Every provider's network I/O goes through here so failures are classified
 * consistently (auth vs. permission vs. transport) instead of leaking raw
 * fetch/SDK errors into the boot path.
 */
const vaultFetch = async (url, { method = 'POST', headers = {}, body = null, timeoutMs = DEFAULT_HTTP_TIMEOUT_MS, provider = null, raw = false } = {}) => {
    let response;

    try {
        response = await fetch(url, {
            method,
            headers: { ...(body ? { 'Content-Type': 'application/json' } : {}), ...headers },
            ...(body ? { body: typeof body === 'string' ? body : JSON.stringify(body) } : {}),
            signal: AbortSignal.timeout(timeoutMs)
        });
    } catch (error) {
        // Transport-level failure: unreachable vault, DNS, TLS, timeout. Always
        // retryable — the key material itself is fine, the network is not.
        throw new KeyVaultError('KEYVAULT::UNREACHABLE', `${provider || 'vault'} request failed: ${error.message}`, { provider, cause: error, retryable: true });
    }

    const text = await response.text();

    if (!response.ok) {
        const detail = text.slice(0, 500);

        if (response.status === 401 || response.status === 403) {
            throw new KeyVaultError('KEYVAULT::AUTH-REJECTED', `${provider || 'vault'} rejected the credentials (HTTP ${response.status}): ${detail}`, { provider });
        }
        if (response.status === 404) {
            throw new KeyVaultError('KEYVAULT::KEY-NOT-FOUND', `${provider || 'vault'} could not find the configured key (HTTP 404): ${detail}`, { provider });
        }

        throw new KeyVaultError('KEYVAULT::REQUEST-FAILED', `${provider || 'vault'} request failed (HTTP ${response.status}): ${detail}`, {
            provider,
            retryable: response.status >= 500
        });
    }

    if (raw) return text;
    if (!text) return {};

    try {
        return JSON.parse(text);
    } catch (error) {
        throw new KeyVaultError('KEYVAULT::MALFORMED-RESPONSE', `${provider || 'vault'} returned a non-JSON response`, { provider, cause: error });
    }
};

/**
 * Caches a bearer token until shortly before it expires. Used by every
 * OAuth-style provider (GCP, Azure, HCP, Akeyless, Vault AppRole).
 */
class TokenCache {
    constructor(refreshFn, skewSeconds = 60) {
        this._refreshFn = refreshFn;
        this._skewMs = skewSeconds * 1000;
        this._token = null;
        this._expiresAt = 0;
        this._inflight = null;
    }

    async get() {
        if (this._token && Date.now() < this._expiresAt - this._skewMs) {
            return this._token;
        }

        // Collapse concurrent refreshes so a burst of wraps triggers one token call.
        if (!this._inflight) {
            this._inflight = (async () => {
                try {
                    const { token, expiresInSeconds } = await this._refreshFn();
                    this._token = token;
                    this._expiresAt = Date.now() + Math.max(Number(expiresInSeconds) || 0, 60) * 1000;
                    return this._token;
                } finally {
                    this._inflight = null;
                }
            })();
        }

        return this._inflight;
    }

    invalidate() {
        this._token = null;
        this._expiresAt = 0;
    }
}

// ─── Base provider ───────────────────────────────────────────────────────────

class KeyVaultProvider {
    /** Stable identifier used in config (`utilities.dataEncryption.provider`). */
    static id = 'ABSTRACT';

    /** 'remote' (vault does the crypto) or 'material' (vault hands back a key). */
    static mode = 'remote';

    /**
     * Human-readable service name, used verbatim in logs and the orchestrator
     * panel so operators see the product they configured, not an enum.
     */
    static displayName = 'Abstract key vault';

    constructor(config = {}) {
        if (new.target === KeyVaultProvider) {
            throw new KeyVaultError('KEYVAULT::ABSTRACT', 'KeyVaultProvider is abstract — instantiate a concrete provider');
        }

        this.config = config;
        this.id = new.target.id;
        this.displayName = new.target.displayName;
        this.mode = new.target.mode;
        this.timeoutMs = Number(config.timeoutMs) > 0 ? Number(config.timeoutMs) : DEFAULT_HTTP_TIMEOUT_MS;
        this.initialized = false;
    }

    /**
     * What this provider can actually do. The key manager consults this rather
     * than special-casing provider ids: a provider that cannot rotate its own
     * KEK reports `rotateKek: false` and the control plane surfaces the DEK
     * rotation path instead of failing.
     */
    get capabilities() {
        return { mode: this.mode, rotateKek: false, keyVersions: false, aad: false };
    }

    /** Provider-identifying reference stored alongside every wrapped DEK. */
    get keyRef() {
        return null;
    }

    async initialize() {
        this.initialized = true;
    }

    async wrapKey() {
        throw new KeyVaultError('KEYVAULT::NOT-IMPLEMENTED', `${this.id} does not implement wrapKey`, { provider: this.id });
    }

    async unwrapKey() {
        throw new KeyVaultError('KEYVAULT::NOT-IMPLEMENTED', `${this.id} does not implement unwrapKey`, { provider: this.id });
    }

    /**
     * Provider-side KEK rotation. Providers that cannot rotate report it rather
     * than throwing — a refusal is an answer, not a failure.
     */
    async rotateKek() {
        return { rotated: false, keyVersion: null, reason: `${this.displayName} does not support key rotation through its API` };
    }

    /**
     * Round-trips a throwaway DEK through wrap + unwrap. This is deliberately a
     * REAL cryptographic round trip and not a metadata read: a vault that
     * answers `GET /key` but cannot decrypt (revoked grant, wrong key version
     * policy, min_decryption_version raised) is exactly the failure that must
     * be caught before the node starts serving.
     */
    async health() {
        const started = Date.now();

        try {
            const probe = crypto.randomBytes(DEK_BYTES);
            const wrapped = await this.wrapKey(probe);
            const returned = await this.unwrapKey(wrapped.blob, { keyRef: wrapped.keyRef, keyVersion: wrapped.keyVersion });

            if (!crypto.timingSafeEqual(probe, returned)) {
                return {
                    ok: false,
                    provider: this.id,
                    displayName: this.displayName,
                    keyRef: this.keyRef,
                    keyVersion: wrapped.keyVersion,
                    latencyMs: Date.now() - started,
                    error: 'round-trip mismatch: the vault returned different key material than it was given'
                };
            }

            return {
                ok: true,
                provider: this.id,
                displayName: this.displayName,
                keyRef: this.keyRef,
                keyVersion: wrapped.keyVersion,
                latencyMs: Date.now() - started,
                error: null
            };
        } catch (error) {
            return {
                ok: false,
                provider: this.id,
                displayName: this.displayName,
                keyRef: this.keyRef,
                keyVersion: null,
                latencyMs: Date.now() - started,
                error: error.message
            };
        }
    }

    async close() {}

    // ── Helpers available to every concrete provider ─────────────────────────

    _request(url, options = {}) {
        return vaultFetch(url, { timeoutMs: this.timeoutMs, provider: this.id, ...options });
    }

    _require(field, value) {
        if (value === undefined || value === null || String(value).trim() === '') {
            throw new KeyVaultError('KEYVAULT::INVALID-CONFIG', `${this.displayName}: utilities.dataEncryption.${field} is required`, { provider: this.id });
        }
        return typeof value === 'string' ? value.trim() : value;
    }

    /** Normalizes a wrap result so every provider returns identical keys. */
    _wrapResult(blob, { keyVersion = null, algorithm = 'vault-managed' } = {}) {
        return { blob: String(blob), keyRef: this.keyRef, keyVersion: keyVersion === null ? null : String(keyVersion), algorithm };
    }

    /** Validates that whatever came back is a usable 32-byte DEK. */
    _assertDek(buf) {
        if (!Buffer.isBuffer(buf) || buf.length !== DEK_BYTES) {
            throw new KeyVaultError('KEYVAULT::BAD-KEY-MATERIAL', `${this.displayName} returned ${Buffer.isBuffer(buf) ? `${buf.length} bytes` : 'a non-buffer'} instead of a ${DEK_BYTES}-byte key`, {
                provider: this.id
            });
        }
        return buf;
    }
}

// ─── Material-mode base ──────────────────────────────────────────────────────

/**
 * For vaults that are secret STORES rather than crypto services. The vault
 * holds high-entropy key material; Orion fetches it and does the wrapping
 * locally with AES-256-GCM, so the caller-visible behaviour is identical to a
 * remote-crypto provider.
 *
 * The security property is weaker and stated plainly: the KEK does reach this
 * process's memory. It never reaches disk or config, it is centrally
 * revocable, and it is auditable at the vault — which is the whole point of
 * moving off a static config string — but a remote-crypto provider is
 * strictly stronger where one is available.
 */
class MaterialKeyVaultProvider extends KeyVaultProvider {
    static mode = 'material';

    constructor(config = {}) {
        super(config);
        this._material = null;
        this._materialVersion = null;
    }

    get capabilities() {
        return { mode: 'material', rotateKek: false, keyVersions: true, aad: true };
    }

    /**
     * Concrete material providers implement this.
     * @returns {Promise<{ material: string, version: string|null }>}
     */
    async fetchKeyMaterial() {
        throw new KeyVaultError('KEYVAULT::NOT-IMPLEMENTED', `${this.id} does not implement fetchKeyMaterial`, { provider: this.id });
    }

    async initialize() {
        await this.refreshMaterial();
        this.initialized = true;
    }

    async refreshMaterial() {
        const { material, version } = await this.fetchKeyMaterial();

        if (!material || String(material).length < 16) {
            throw new KeyVaultError('KEYVAULT::WEAK-KEY-MATERIAL', `${this.displayName}: the stored key material is missing or shorter than 16 characters`, {
                provider: this.id
            });
        }

        // sha256-derived so any high-entropy string the operator stored in the
        // vault becomes a valid 32-byte AES key, exactly as the legacy inline
        // key behaved.
        this._material = crypto.createHash('sha256').update(String(material)).digest();
        this._materialVersion = version === undefined || version === null ? null : String(version);

        return this._materialVersion;
    }

    _kek() {
        if (!this._material) {
            throw new KeyVaultError('KEYVAULT::NOT-INITIALIZED', `${this.displayName}: key material has not been fetched yet`, { provider: this.id });
        }
        return this._material;
    }

    async wrapKey(dek) {
        const iv = crypto.randomBytes(12);
        const cipher = crypto.createCipheriv('aes-256-gcm', this._kek(), iv);
        cipher.setAAD(Buffer.from(JSON.stringify(WRAP_CONTEXT), 'utf8'));

        const ciphertext = Buffer.concat([cipher.update(dek), cipher.final()]);
        const tag = cipher.getAuthTag();

        return this._wrapResult(`m1.${b64(iv)}.${b64(tag)}.${b64(ciphertext)}`, { keyVersion: this._materialVersion, algorithm: 'AES-256-GCM (local wrap)' });
    }

    async unwrapKey(blob, { keyVersion = null } = {}) {
        const parts = String(blob).split('.');

        if (parts.length !== 4 || parts[0] !== 'm1') {
            throw new KeyVaultError('KEYVAULT::MALFORMED-BLOB', `${this.displayName}: wrapped key is not in the expected local-wrap format`, { provider: this.id });
        }

        // The vault rotated the stored material after this DEK was wrapped.
        // Re-fetch once — the operator may have rotated between boots — and only
        // then give up, so a benign rotation does not look like corruption.
        if (keyVersion && this._materialVersion && keyVersion !== this._materialVersion) {
            await this.refreshMaterial();
        }

        try {
            const decipher = crypto.createDecipheriv('aes-256-gcm', this._kek(), unb64(parts[1]));
            decipher.setAAD(Buffer.from(JSON.stringify(WRAP_CONTEXT), 'utf8'));
            decipher.setAuthTag(unb64(parts[2]));
            return this._assertDek(Buffer.concat([decipher.update(unb64(parts[3])), decipher.final()]));
        } catch (error) {
            throw new KeyVaultError('KEYVAULT::UNWRAP-FAILED', `${this.displayName}: the stored key material does not decrypt this wrapped key — it was almost certainly rotated or replaced`, {
                provider: this.id,
                cause: error
            });
        }
    }
}

export { KeyVaultProvider, MaterialKeyVaultProvider, KeyVaultError, TokenCache, vaultFetch, b64, unb64, b64url, unb64url, DEK_BYTES, WRAP_CONTEXT, DEFAULT_HTTP_TIMEOUT_MS };
