import { SafeModuleHandler } from '../../UnavailableModuleWrapper.js';
import { logger } from '../../logger.js';

const dbModule = new SafeModuleHandler('Database', 'db', 'TOTPModel.js');

const query = (text, params) => dbModule.getModule().query(text, params);

// ─── Encryption at rest ──────────────────────────────────────────────────────
// TOTP secrets are sealed before they touch the database, so a database dump
// alone cannot compromise 2FA. All key handling lives in the key vault
// subsystem (Utils/Core/KeyVault): a data encryption key generated by Orion and
// stored wrapped by a key encryption key that lives in AWS KMS, Cloud KMS,
// Azure Key Vault, Vault/OpenBao transit, or — single instance only — a key in
// orion.config.js.
//
// Two rules this file exists to enforce:
//
//   1. NEVER write a secret in plaintext. Earlier releases fell back to
//      plaintext with a warning when no key was configured; a silent downgrade
//      of at-rest protection is not an acceptable default. Without encryption,
//      writes are refused and TOTP deactivates.
//
//   2. NEVER throw on read. An unreadable secret returns null, and callers
//      treat that as "this user's authenticator is unavailable" and offer the
//      emailed one-time code instead. Throwing here would turn a key-vault
//      outage into 500s on the login path.

const encryptionModule = new SafeModuleHandler('EncryptionKeyManager', 'encryptionKeyManager', 'TOTPModel.js');

let warnedUnavailable = false;

const keyManager = () => encryptionModule.probeModule();

/**
 * @throws when field encryption is unavailable — the caller must surface this
 *         as a deactivated feature, never as a plaintext write.
 */
const seal = async plain => {
    if (plain === null || plain === undefined) return plain;

    const manager = keyManager();

    if (!manager?.available) {
        throw new Error(
            'TOTPModel: refusing to store a TOTP secret because field encryption is unavailable' +
                `${manager?.unavailableReason ? ` — ${manager.unavailableReason}` : ''}. TOTP is deactivated until a key vault is reachable.`
        );
    }

    return manager.seal(plain);
};

/** @returns {Promise<string|null>} null when the value exists but cannot be decrypted. */
const open = async stored => {
    if (stored === null || stored === undefined) return stored;

    const manager = keyManager();

    if (!manager?.available) {
        // A legacy plaintext row is still readable with no key at all; anything
        // sealed is not, and that is reported as unavailable rather than fatal.
        const value = String(stored);
        if (!value.startsWith('enc.v1.') && !value.startsWith('enc.v2.')) return value;

        if (!warnedUnavailable) {
            warnedUnavailable = true;
            logger.error('TOTPModel: encrypted TOTP secrets exist but field encryption is unavailable — affected users fall back to the emailed one-time code');
        }

        return null;
    }

    return manager.open(stored);
};

/** True when this node can read and write TOTP secrets at all. */
const totpStorageAvailable = () => keyManager()?.available === true;

// ─── Model ───────────────────────────────────────────────────────────────────

export const TOTPModel = {
    async savePendingSecret(uid, secret) {
        const sealed = await seal(secret);

        await query(
            `INSERT INTO user_totp (user_uid, pending_secret)
             VALUES ($1, $2)
             ON CONFLICT (user_uid)
             DO UPDATE SET pending_secret = EXCLUDED.pending_secret, updated_at = NOW()`,
            [uid, sealed]
        );
    },

    /**
     * Promote the pending secret to active, enable TOTP.
     */
    async enableTOTP(uid, secret) {
        const sealed = await seal(secret);

        await query(
            `INSERT INTO user_totp (user_uid, enabled, secret, pending_secret)
             VALUES ($1, true, $2, NULL)
             ON CONFLICT (user_uid)
             DO UPDATE SET enabled = true, secret = EXCLUDED.secret, pending_secret = NULL, updated_at = NOW()`,
            [uid, sealed]
        );
    },

    async disableTOTP(uid) {
        await query(
            `UPDATE user_totp SET enabled = false, secret = NULL, pending_secret = NULL, updated_at = NOW()
             WHERE user_uid = $1`,
            [uid]
        );
    },

    /**
     * @returns {{ enabled, secret, pending_secret } | null} secrets are decrypted;
     *          a secret that cannot be decrypted comes back as null while
     *          `enabled` still reports what the account claims — callers need
     *          both facts to tell "no TOTP" apart from "TOTP unreadable".
     */
    async getTOTPConfig(uid) {
        const result = await query('SELECT * FROM user_totp WHERE user_uid = $1', [uid]);
        const row = result.rows[0];
        if (!row) return null;

        row.secret = await open(row.secret);
        row.pending_secret = await open(row.pending_secret);
        return row;
    },

    async isEnabled(uid) {
        const result = await query('SELECT enabled FROM user_totp WHERE user_uid = $1', [uid]);
        return result.rows[0]?.enabled || false;
    },

    /**
     * Whether this user can actually complete a TOTP challenge right now:
     * enrolled AND their secret is readable on this node. This is the check the
     * 2FA method lists use, so a user whose secret cannot be decrypted is
     * offered the emailed code instead of a factor that would always fail.
     */
    async isUsable(uid) {
        const result = await query('SELECT enabled, secret FROM user_totp WHERE user_uid = $1', [uid]);
        const row = result.rows[0];

        if (!row?.enabled || !row.secret) return false;

        return (await open(row.secret)) !== null;
    },

    async getSecret(uid) {
        const result = await query('SELECT secret FROM user_totp WHERE user_uid = $1', [uid]);
        return open(result.rows[0]?.secret || null);
    },

    async getPendingSecret(uid) {
        const result = await query('SELECT pending_secret FROM user_totp WHERE user_uid = $1', [uid]);
        return open(result.rows[0]?.pending_secret || null);
    }
};

// Exported for unit tests and for the boot-time availability checks.
export const __sealing = { seal, open, totpStorageAvailable };
